[package]
name = "daux-graphics-egui"
description = "egui integration for DAUx plug-in editors."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
daux-graphics = { workspace = true }
daux-parameter = { workspace = true }
egui = { workspace = true }

[lints]
workspace = true
