[package]
name = "daux-example-gain-egui"
description = "Gain effect with an egui editor."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
daux-plugin = { workspace = true, features = ["axt", "egui"] }

[lints]
workspace = true
