[package]
name = "daux-events"
description = "Format-neutral, sample-accurate event model for DAUxPlug."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
daux-midi = { workspace = true }

[lints]
workspace = true
