[package]
name = "daux-example-analyzer-gpui"
description = "Spectrum analyzer with a GPUI editor (experimental)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
daux-plugin = { workspace = true, features = ["axt", "gpui"] }

[lints]
workspace = true
