//! Versioned plug-in state serialization and migration for DAUxPlug.
//!
//! A plug-in's state is the one thing a user cannot afford to lose. This crate is the
//! deterministic, self-describing binary container the SDK saves it in, plus the migration
//! machinery that keeps ten-year-old projects loadable.
//!
//! It has **no dependencies** (the `serde` feature is optional and off by default) and
//! contains no `unsafe`.
//!
//! # The container
//!
//! A blob is a 20-byte header — magic `DAUXST\0\0`, container format version, plug-in
//! schema version, entry count — followed by length-prefixed `(key, type tag, value)`
//! entries in insertion order, all little-endian. Values are `f64`, `i64`, `bool`, `str`,
//! `bytes`, or a nested group delimited by begin/end markers. [`mod@format`] documents
//! the layout byte for byte.
//!
//! Encoding is **deterministic**: the same sequence of `put_*` calls always yields exactly
//! the same bytes, so state hashes are stable and a diff of two saved projects is
//! meaningful. Nothing about the machine, the moment or hash-map iteration order can leak
//! in.
//!
//! ```
//! use daux_state::{StateReader, StateVersion, StateWriter};
//!
//! let mut w = StateWriter::new(StateVersion(1));
//! w.put_f64("gain", -6.0);
//! w.begin_group("filter");
//! w.put_str("mode", "lowpass");
//! w.put_f64("cutoff", 1_000.0);
//! w.end_group();
//! let bytes = w.try_finish()?;
//!
//! let r = StateReader::from_bytes(&bytes)?;
//! assert_eq!(r.f64("gain")?, -6.0);
//! assert_eq!(r.str("filter/mode")?, "lowpass");        // '/' walks into groups
//! assert_eq!(r.group("filter")?.f64("cutoff")?, 1_000.0);
//! assert_eq!(r.opt_f64("filter/resonance"), None);     // never written, never invented
//! # Ok::<(), daux_state::StateError>(())
//! ```
//!
//! # Parsing is hostile-input handling
//!
//! Project files travel: they are e-mailed, downloaded, generated by scripts and edited by
//! other tools. Everything a host hands a plug-in is therefore untrusted, and the parser
//! treats it that way.
//!
//! * A blob larger than [`StateLimits::max_blob_bytes`] (64 MiB by default) is rejected
//!   before it is looked at, and [`StateReader::read_from`] stops pulling from a stream
//!   at that bound so an endless pipe cannot exhaust memory.
//! * Every length prefix is checked against the configured maximum **and** against the
//!   bytes actually remaining in the input, so nothing is ever allocated on the strength
//!   of a number the attacker chose. Total allocation is bounded by the input size.
//! * Keys are bounded ([`StateLimits::max_key_bytes`], 4 KiB), entry counts are bounded,
//!   and group nesting is bounded ([`StateLimits::max_depth`], 64) — which also bounds the
//!   recursive drop of the resulting tree.
//! * Unknown type tags, non-`0`/`1` boolean bytes, invalid UTF-8, unbalanced groups,
//!   trailing bytes and entry-count mismatches are all errors.
//! * Nothing in this crate panics on malformed input, and there is no `unsafe`.
//!
//! # Versioning and migration
//!
//! [`StateVersion`] is the plug-in's *schema* version, independent of the container
//! format. abi-v1 §12 requires a plug-in to load every schema version it has ever shipped,
//! or fail cleanly with no side effects. [`MigrationChain`] does that with one small
//! `from → from + 1` [`StateDoc`] rewrite per version bump:
//!
//! ```
//! use daux_state::{MigrationChain, StateDoc, StateVersion};
//!
//! let chain = MigrationChain::new(StateVersion(3))
//!     .step(StateVersion(1), |doc| doc.rename("gain_db", "gain"))
//!     .step(StateVersion(2), |doc| { doc.insert("bypass", false)?; Ok(()) });
//!
//! let mut old = StateDoc::new(StateVersion(1));
//! old.insert("gain_db", -6.0)?;
//!
//! let now = chain.migrate(old)?;
//! assert_eq!(now.version(), StateVersion(3));
//! assert_eq!(now.f64("gain")?, -6.0);
//! # Ok::<(), daux_state::StateError>(())
//! ```
//!
//! Migration is all-or-nothing: a failing step aborts and the partially rewritten document
//! is dropped, so a host never observes a half-applied load.
//!
//! # Threading
//!
//! Everything here is `[main-thread]`. Saving and loading allocate, and abi-v1 §11.3 only
//! ever calls `daux.state/1` on the main thread; nothing in this crate may be called from
//! `process`.

#![forbid(unsafe_code)]

mod codec;
mod doc;
mod error;
pub mod format;
mod limits;
mod migrate;
mod reader;
mod value;
mod version;
mod writer;

pub use doc::{StateDoc, StateGroup};
pub use error::{StateError, StateErrorKind, StateResult};
pub use limits::StateLimits;
pub use migrate::{MigrationChain, MigrationStep};
pub use reader::StateReader;
pub use value::{StateEntry, Value, ValueType};
pub use version::StateVersion;
pub use writer::StateWriter;

#[cfg(test)]
mod tests {
    use super::*;

    /// The end-to-end shape a `DauxController` implementation actually uses.
    #[test]
    fn save_load_migrate_round_trip() {
        // The plug-in as it shipped in v1.
        let mut w = StateWriter::new(StateVersion(1));
        w.put_f64("gain_db", -6.0);
        w.put_bool("invert", true);
        w.begin_group("filter");
        w.put_str("mode", "lowpass");
        w.put_f64("cutoff", 800.0);
        w.end_group();
        let saved_by_v1 = w.try_finish().expect("valid");

        // The plug-in as it ships today.
        let chain = MigrationChain::new(StateVersion(3))
            .step(StateVersion(1), |doc| {
                doc.rename("gain_db", "gain")?;
                doc.rename("invert", "filter/invert")
            })
            .step(StateVersion(2), |doc| {
                doc.insert("bypass", false)?;
                Ok(())
            });

        let doc = chain.migrate_bytes(&saved_by_v1).expect("migrates");
        assert_eq!(doc.version(), StateVersion(3));
        assert_eq!(doc.f64("gain"), Ok(-6.0));
        assert_eq!(doc.bool("filter/invert"), Ok(true));
        assert_eq!(doc.str("filter/mode"), Ok("lowpass"));
        assert_eq!(doc.f64("filter/cutoff"), Ok(800.0));
        assert_eq!(doc.bool("bypass"), Ok(false));

        // Saving again produces a v3 blob that needs no migration at all.
        let saved_by_v3 = doc.try_to_bytes().expect("encodes");
        let reloaded = chain.migrate_bytes(&saved_by_v3).expect("no-op migration");
        assert_eq!(reloaded, doc);
    }

    #[test]
    fn everything_public_is_send_and_sync() {
        const fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<StateDoc>();
        assert_send_sync::<StateReader>();
        assert_send_sync::<StateWriter>();
        assert_send_sync::<StateError>();
        assert_send_sync::<StateLimits>();
        assert_send_sync::<StateVersion>();
        assert_send_sync::<MigrationChain>();
        assert_send_sync::<Value>();
        assert_send_sync::<StateEntry>();
    }

    #[test]
    fn a_deeply_nested_document_survives_a_round_trip_and_its_own_drop() {
        let depth = StateLimits::DEFAULT_MAX_DEPTH;
        let mut w = StateWriter::new(StateVersion(1));
        for i in 0..depth {
            w.begin_group(&format!("g{i}"));
        }
        w.put_i64("deep", 42);
        for _ in 0..depth {
            w.end_group();
        }
        let bytes = w.try_finish().expect("valid");

        let mut path = String::new();
        for i in 0..depth {
            path.push_str(&format!("g{i}/"));
        }
        path.push_str("deep");

        let r = StateReader::from_bytes(&bytes).expect("decodes");
        assert_eq!(r.i64(&path), Ok(42));
        drop(r);

        // One level past the limit must be refused rather than parsed.
        let limits = StateLimits::default().with_max_depth(depth - 1);
        assert_eq!(
            StateReader::from_bytes_with_limits(&bytes, &limits)
                .expect_err("too deep")
                .kind(),
            &StateErrorKind::LimitExceeded
        );
    }

    #[test]
    fn a_large_but_legal_document_round_trips() {
        let mut w = StateWriter::new(StateVersion(1));
        for i in 0..5_000i64 {
            w.put_i64(&format!("param{i}"), i * 3);
        }
        let bytes = w.try_finish().expect("valid");
        let r = StateReader::from_bytes(&bytes).expect("decodes");
        assert_eq!(r.len(), 5_000);
        assert_eq!(r.i64("param4999"), Ok(14_997));
    }

    #[test]
    fn every_truncation_of_a_realistic_blob_is_rejected_cleanly() {
        let mut w = StateWriter::new(StateVersion(2));
        w.put_f64("gain", -6.0);
        w.put_str("preset", "Init");
        w.begin_group("filter");
        w.put_bytes("curve", &[1, 2, 3, 4, 5, 6, 7, 8]);
        w.end_group();
        let bytes = w.try_finish().expect("valid");

        for len in 0..bytes.len() {
            assert!(
                StateReader::from_bytes(&bytes[..len]).is_err(),
                "a {len}-byte prefix must not parse"
            );
        }
        assert!(StateReader::from_bytes(&bytes).is_ok());
    }

    #[test]
    fn appending_garbage_is_rejected() {
        let mut w = StateWriter::new(StateVersion(1));
        w.put_i64("n", 1);
        let mut bytes = w.try_finish().expect("valid");
        bytes.extend_from_slice(b"trailing junk");
        let err = StateReader::from_bytes(&bytes).expect_err("must fail");
        assert_eq!(err.kind(), &StateErrorKind::Corrupt);
        assert!(err.to_string().contains("trailing"));
    }

    #[test]
    fn a_blob_from_another_tool_is_rejected_not_misread() {
        for foreign in [
            &b"{\"gain\": -6.0}"[..],
            &b"RIFF\0\0\0\0WAVEfmt "[..],
            &[0xff; 64][..],
            &[0x00; 1024][..],
        ] {
            assert!(StateReader::from_bytes(foreign).is_err());
        }
    }
}
