[package]
name = "daux-abi"
description = "Stable C-compatible ABI definitions for the DAUx Audio Extension (.axt) format."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true



[lints]
workspace = true
