[package]
name = "daux-midi"
description = "MIDI 1.0 and MIDI 2.0 / UMP message types for DAUxPlug."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true



[lints]
workspace = true
